# Generated by Django 4.1.6 on 2023-02-14 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_categories', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_subcategory', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categories')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoriesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_category', models.CharField(max_length=255, null=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategories')),
            ],
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=255)),
                ('price', models.PositiveSmallIntegerField()),
                ('product_description', models.JSONField(null=True)),
                ('currency', models.IntegerField(choices=[(0, 'EUR'), (1, 'USD'), (2, 'MDL')], default=2)),
                ('images', models.ImageField(null=True, upload_to='media/products')),
                ('created_date', models.DateField(auto_now=True)),
                ('updated_date', models.DateField(null=True)),
                ('checkout', models.BooleanField(default=False)),
                ('SubCategoriesType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategoriestype')),
            ],
        ),
    ]
