# Generated by Django 4.1.5 on 2023-02-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_images_produs_image_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='product',
            new_name='produs',
        ),
    ]
