# Generated by Django 4.1.5 on 2023-02-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_produs_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='image',
            field=models.ImageField(null=True, upload_to='media/products'),
        ),
    ]
