# Generated by Django 4.1.5 on 2023-02-15 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_produs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='produs',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.produs'),
        ),
        migrations.AlterField(
            model_name='produs',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='media/products'),
        ),
    ]
