# Generated by Django 4.1.5 on 2023-02-15 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_images_image_alter_images_produs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produs',
            name='image',
        ),
    ]
