# Generated by Django 4.1.5 on 2023-02-15 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_produs_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produs',
            name='image',
        ),
    ]
