# Generated by Django 4.1.5 on 2023-02-15 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_produs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='SubCategoriesType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.subcategoriestype'),
        ),
    ]
