# Generated by Django 4.1.5 on 2023-02-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_produs_subcategoriestype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produs',
            name='image',
        ),
    ]
