# Generated by Django 4.1.6 on 2023-02-23 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_images_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produs',
            old_name='nume',
            new_name='name',
        ),
    ]
